# Generated by Django 4.2.4 on 2023-08-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('phoneNumber', models.BigIntegerField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('userpass1', models.CharField(max_length=150)),
                ('userpass2', models.CharField(max_length=150)),
            ],
        ),
    ]
